version: '3.5' 

services: 
  frontend:
    image: example-frontend
    ports:
      - 8081:5000
  backend:
    image: example-backend
    ports:
      - 4564:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
  redis:
    image: redis
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db:/var/lib/postgresql/data
